apiVersion: v2
name: chart
description: A multi-tenanted platform to build agents and workflows
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - ai
  - agents
  - workflows
  - automation
home: https://example.com
sources:
  - https://github.com/ensembleui/workflows
maintainers:
  - name: Ensemble Technologies
    email: support@ensembleui.com
