
environments:
  required:
    - CLOUD_PROVIDER # aws, gcp
    - SERVERLESS_ENVIRONMENT # true, false
    - SERVER_URL
    - STORAGE_USER_FILES_BUCKET
    - STORAGE_DOCUMENTS_BUCKET
    - STORAGE_TENANT_MIGRATIONS_BUCKET
    - KMS_SECRETS_KEYRING
    - KMS_SECRETS_KEY
    - KMS_CONNECTIONS_KEYRING
    - KMS_CONNECTIONS_KEY
    - KMS_ENVIRONMENT_KEYRING
    - KMS_ENVIRONMENT_KEY
  required[aws]:
    - AWS_REGION
  required[gpc]:
    - GOOGLE_CLOUD_PROJECT
    - GCP_REGION
    - GCP_SERVICE_ACCOUNT
    - KMS_LOCATION_ID
  optional:
    - TEMPORAL_HOST
    - TEMPORAL_NAMESPACE
    - TEMPORAL_TASK_QUEUE

secrets:
  required:
    - PG_BASE_URL
    - TEMPORAL_API_KEY
  optional:
    - SYSTEM_DB_NAME
    - GOOGLE_MAPS_API_KEY
    - BRAVE_SEARCH_API_KEY
    - ELEVENLABS_API_KEY
    - AIRTABLE_API_KEY
    # Slack
    - SLACK_BOT_TOKEN
    - SLACK_SIGNING_SECRET
    # Twilio
    - TWILIO_ACCOUNT_SID
    - TWILIO_API_KEY_SID
    - TWILIO_API_KEY_SECRET
    - TWILIO_AUTH_TOKEN
    - TWILIO_PHONE_NUMBER
    # Built-in LLM
    - OPENAI_API_KEY
    - ANTHROPIC_API_KEY
    - DEEPSEEK_API_KEY
    - GEMINI_API_KEY
    - CEREBRAS_API_KEY
    - MOONSHOTAI_API_KEY
    - ZHIPU_API_KEY
    # Neon database
    - NEON_API_KEY
    - NEON_BRANCH
    - NEON_OWNER_NAME
    - NEON_PROJECT
    # Email service
    - RESEND_API_KEY
    - SENDGRID_API_KEY
  
